import SwiftUI
import CoreData
import AppKit

struct RelazionePeritaleView: View {
    @ObservedObject var sinistro: Sinistro
    @Binding var perizia: Perizia?
    @Environment(\.managedObjectContext) private var viewContext
    
    // MARK: - State
    @State private var relazionePerizia: String = ""
    @State private var noteConclusive: String = ""
    @State private var noteRiserva: String = ""
    @State private var noteOsservazioni: String = ""
    @State private var hasRiserva: Bool = false
    @State private var eventoCausatoDa: String = ""
    @State private var determinazione: String = ""
    
    @State private var isGeneratingRelazione: Bool = false
    @State private var showRiserveMenu: Bool = false
    
    // Versioning - ora caricato da Core Data
    @State private var versioniRelazione: [String] = []
    @State private var versioniNoteConclusive: [String] = []
    @State private var versioniNoteRiserva: [String] = []
    @State private var versioniNoteOsservazioni: [String] = []
    @State private var indiceVersioneRelazione: Int = -1
    @State private var indiceVersioneNoteConclusive: Int = -1
    @State private var indiceVersioneNoteRiserva: Int = -1
    @State private var indiceVersioneNoteOsservazioni: Int = -1
    
    // Generazione automatica
    @State private var hasAutoGenerated: Bool = false
    @State private var lastPeriziaHash: Int = 0
    
    // MARK: - Services
    private let relazioneService = RelazionePeritaleService.shared
    
    // MARK: - Limiti
    private let limiteRelazione = RelazionePeritaleService.limiteRelazionePerizia
    private let limiteRiserve = RelazionePeritaleService.limiteRiserve
    private let limiteOsservazioni = RelazionePeritaleService.limiteOsservazioni
    
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 24) {
                // MARK: - Evento causato da + Determinazione
                eventoEDeterminazioneSection
                
                // MARK: - Relazione di perizia
                relazionePeriziaSection
                
                // MARK: - Note conclusive
                noteConclusiveSection
                
                // MARK: - Riserva / Osservazioni
                riservaOsservazioniSection
            }
            .padding(20)
        }
        .onAppear {
            loadValues()
            checkAutoGeneration()
        }
        .onChange(of: perizia?.objectID) { _ in
            loadValues()
            checkAutoGeneration()
        }
        .onChange(of: perizia?.partite) { _ in
            // Rigenera automaticamente quando cambiano i beni
            if hasAutoGenerated {
                checkAutoGeneration()
            }
        }
    }
    
    // MARK: - Sezione Evento e Determinazione
    
    private var eventoEDeterminazioneSection: some View {
        GroupBox {
            VStack(alignment: .leading, spacing: 12) {
                // Evento causato da
                VStack(alignment: .leading, spacing: 8) {
                    HStack {
                        Label("Evento Causato Da", systemImage: "bolt.fill")
                            .font(.headline)
                        
                        Spacer()
                        
                        Button {
                            let defaultEvento = relazioneService.generaEventoCausatoDa(sinistro: sinistro, perizia: perizia)
                            if !defaultEvento.isEmpty {
                                eventoCausatoDa = defaultEvento
                                saveChanges()
                            }
                        } label: {
                            Label("Default", systemImage: "wand.and.stars")
                                .font(.caption)
                        }
                        .buttonStyle(.bordered)
                        .controlSize(.small)
                    }
                    
                    TextField("Descrivi brevemente l'evento...", text: $eventoCausatoDa, axis: .vertical)
                        .lineLimit(2...4)
                        .textFieldStyle(.roundedBorder)
                        .onChange(of: eventoCausatoDa) { _ in saveChanges() }
                }
                
                Divider()
                
                // Determinazione
                VStack(alignment: .leading, spacing: 8) {
                    HStack {
                        Label("Determinazione", systemImage: "checkmark.circle")
                            .font(.headline)
                        
                        Spacer()
                        
                        if let suggerita = relazioneService.derivaDeterminazione(da: sinistro) {
                            Text("Suggerita: \(suggerita)")
                                .font(.caption)
                                .foregroundColor(.secondary)
                        }
                    }
                    
                    Picker("Determinazione", selection: $determinazione) {
                        Text("Seleziona...").tag("")
                        ForEach(RelazionePeritaleService.opzioniDeterminazione, id: \.self) { opzione in
                            Text(opzione).tag(opzione)
                        }
                    }
                    .pickerStyle(.menu)
                    .onChange(of: determinazione) { _ in
                        perizia?.determinazione = determinazione.isEmpty ? nil : determinazione
                        saveChanges()
                    }
                }
            }
            .padding(.vertical, 4)
        }
    }
    
    // MARK: - Sezione Relazione Peritale
    
    private var relazionePeriziaSection: some View {
        GroupBox {
            VStack(alignment: .leading, spacing: 8) {
                HStack {
                    Label("Relazione di Perizia", systemImage: "doc.text")
                        .font(.headline)
                    
                    Spacer()
                    
                    // Versioning
                    if !versioniRelazione.isEmpty {
                        HStack(spacing: 4) {
                            Button {
                                navigaVersionePrecedente(field: .relazione)
                            } label: {
                                Image(systemName: "chevron.left")
                                    .font(.caption)
                            }
                            .buttonStyle(.borderless)
                            .disabled(indiceVersioneRelazione <= 0)
                            
                            Text("v\(indiceVersioneRelazione + 1)/\(versioniRelazione.count)")
                                .font(.caption2)
                                .foregroundColor(.secondary)
                            
                            Button {
                                navigaVersioneSuccessiva(field: .relazione)
                            } label: {
                                Image(systemName: "chevron.right")
                                    .font(.caption)
                            }
                            .buttonStyle(.borderless)
                            .disabled(indiceVersioneRelazione >= versioniRelazione.count - 1)
                        }
                    }
                    
                    // Pulsante copia
                    Button {
                        copiaTesto(relazionePerizia)
                    } label: {
                        Label("Copia", systemImage: "doc.on.doc")
                            .font(.caption)
                    }
                    .buttonStyle(.bordered)
                    .controlSize(.small)
                    .disabled(relazionePerizia.isEmpty)
                    
                    // Pulsante genera
                    Button {
                        generaRelazione()
                    } label: {
                        Label("Genera", systemImage: "sparkles")
                            .font(.caption)
                    }
                    .buttonStyle(.bordered)
                    .controlSize(.small)
                    .disabled(perizia == nil || isGeneratingRelazione)
                    
                    // Pulsante IA (miglioramento)
                    Button {
                        miglioraRelazioneConIA()
                    } label: {
                        Label("IA", systemImage: "brain")
                            .font(.caption)
                    }
                    .buttonStyle(.borderedProminent)
                    .controlSize(.small)
                    .disabled(relazionePerizia.isEmpty || isGeneratingRelazione)
                }
                
                Text("Descrizione completa della perizia, analisi del danno e valutazioni tecniche")
                    .font(.caption)
                    .foregroundColor(.secondary)
                
                TextEditor(text: $relazionePerizia)
                    .frame(minHeight: 200)
                    .font(.system(size: 13))
                    .padding(4)
                    .background(Color(NSColor.textBackgroundColor))
                    .cornerRadius(6)
                    .overlay(
                        RoundedRectangle(cornerRadius: 6)
                            .stroke(caratteriColor(relazionePerizia.count, limite: limiteRelazione).opacity(0.3), lineWidth: 1)
                    )
                    .onChange(of: relazionePerizia) { newValue in
                        salvaVersione(field: .relazione, valore: newValue)
                        saveChanges()
                    }
                
                HStack {
                    if isGeneratingRelazione {
                        ProgressView()
                            .scaleEffect(0.7)
                        Text("Generazione in corso...")
                            .font(.caption)
                            .foregroundColor(.secondary)
                    }
                    
                    Spacer()
                    
                    Text("\(relazionePerizia.count)/\(limiteRelazione) caratteri")
                        .font(.caption)
                        .foregroundColor(caratteriColor(relazionePerizia.count, limite: limiteRelazione))
                }
            }
            .padding(.vertical, 4)
        }
    }
    
    // MARK: - Sezione Note Conclusive
    
    private var noteConclusiveSection: some View {
        GroupBox {
            VStack(alignment: .leading, spacing: 8) {
                HStack {
                    Label("Note Conclusive", systemImage: "checkmark.seal")
                        .font(.headline)
                    
                    Spacer()
                    
                    // Versioning
                    if !versioniNoteConclusive.isEmpty {
                        HStack(spacing: 4) {
                            Button {
                                navigaVersionePrecedente(field: .noteConclusive)
                            } label: {
                                Image(systemName: "chevron.left")
                                    .font(.caption)
                            }
                            .buttonStyle(.borderless)
                            .disabled(indiceVersioneNoteConclusive <= 0)
                            
                            Text("v\(indiceVersioneNoteConclusive + 1)/\(versioniNoteConclusive.count)")
                                .font(.caption2)
                                .foregroundColor(.secondary)
                            
                            Button {
                                navigaVersioneSuccessiva(field: .noteConclusive)
                            } label: {
                                Image(systemName: "chevron.right")
                                    .font(.caption)
                            }
                            .buttonStyle(.borderless)
                            .disabled(indiceVersioneNoteConclusive >= versioniNoteConclusive.count - 1)
                        }
                    }
                    
                    // Pulsante copia
                    Button {
                        copiaTesto(noteConclusive)
                    } label: {
                        Label("Copia", systemImage: "doc.on.doc")
                            .font(.caption)
                    }
                    .buttonStyle(.bordered)
                    .controlSize(.small)
                    .disabled(noteConclusive.isEmpty)
                    
                    Button {
                        generaNoteConclusive()
                    } label: {
                        Label("Genera", systemImage: "sparkles")
                            .font(.caption)
                    }
                    .buttonStyle(.bordered)
                    .controlSize(.small)
                    .disabled(perizia == nil)
                }
                
                Text("Conclusioni e considerazioni finali della perizia")
                    .font(.caption)
                    .foregroundColor(.secondary)
                
                TextEditor(text: $noteConclusive)
                    .frame(minHeight: 100)
                    .font(.system(size: 13))
                    .padding(4)
                    .background(Color(NSColor.textBackgroundColor))
                    .cornerRadius(6)
                    .overlay(
                        RoundedRectangle(cornerRadius: 6)
                            .stroke(Color.gray.opacity(0.3), lineWidth: 1)
                    )
                    .onChange(of: noteConclusive) { newValue in
                        salvaVersione(field: .noteConclusive, valore: newValue)
                        saveChanges()
                    }
                
                HStack {
                    Spacer()
                    Text("\(noteConclusive.count) caratteri")
                        .font(.caption)
                        .foregroundColor(.secondary)
                }
            }
            .padding(.vertical, 4)
        }
    }
    
    // MARK: - Sezione Riserva / Osservazioni
    
    private var riservaOsservazioniSection: some View {
        GroupBox {
            VStack(alignment: .leading, spacing: 12) {
                HStack {
                    Label("Riserva / Osservazioni", systemImage: "exclamationmark.bubble")
                        .font(.headline)
                    
                    Spacer()
                    
                    // Versioning (per riserva o osservazioni)
                    if hasRiserva && !versioniNoteRiserva.isEmpty {
                        HStack(spacing: 4) {
                            Button {
                                navigaVersionePrecedente(field: .noteRiserva)
                            } label: {
                                Image(systemName: "chevron.left")
                                    .font(.caption)
                            }
                            .buttonStyle(.borderless)
                            .disabled(indiceVersioneNoteRiserva <= 0)
                            
                            Text("v\(indiceVersioneNoteRiserva + 1)/\(versioniNoteRiserva.count)")
                                .font(.caption2)
                                .foregroundColor(.secondary)
                            
                            Button {
                                navigaVersioneSuccessiva(field: .noteRiserva)
                            } label: {
                                Image(systemName: "chevron.right")
                                    .font(.caption)
                            }
                            .buttonStyle(.borderless)
                            .disabled(indiceVersioneNoteRiserva >= versioniNoteRiserva.count - 1)
                        }
                    } else if !hasRiserva && !versioniNoteOsservazioni.isEmpty {
                        HStack(spacing: 4) {
                            Button {
                                navigaVersionePrecedente(field: .noteOsservazioni)
                            } label: {
                                Image(systemName: "chevron.left")
                                    .font(.caption)
                            }
                            .buttonStyle(.borderless)
                            .disabled(indiceVersioneNoteOsservazioni <= 0)
                            
                            Text("v\(indiceVersioneNoteOsservazioni + 1)/\(versioniNoteOsservazioni.count)")
                                .font(.caption2)
                                .foregroundColor(.secondary)
                            
                            Button {
                                navigaVersioneSuccessiva(field: .noteOsservazioni)
                            } label: {
                                Image(systemName: "chevron.right")
                                    .font(.caption)
                            }
                            .buttonStyle(.borderless)
                            .disabled(indiceVersioneNoteOsservazioni >= versioniNoteOsservazioni.count - 1)
                        }
                    }
                    
                    // Pulsante copia
                    Button {
                        copiaTesto(hasRiserva ? noteRiserva : noteOsservazioni)
                    } label: {
                        Label("Copia", systemImage: "doc.on.doc")
                            .font(.caption)
                    }
                    .buttonStyle(.bordered)
                    .controlSize(.small)
                    .disabled(hasRiserva ? noteRiserva.isEmpty : noteOsservazioni.isEmpty)
                    
                    // Pulsante genera automatico
                    Button {
                        if hasRiserva {
                            generaRiserve()
                        } else {
                            generaOsservazioni()
                        }
                    } label: {
                        Label("Genera", systemImage: "sparkles")
                            .font(.caption)
                    }
                    .buttonStyle(.bordered)
                    .controlSize(.small)
                    .disabled(perizia == nil)
                }
                
                // Selettore tipo
                HStack(spacing: 20) {
                    Toggle("Riserva", isOn: Binding(
                        get: { hasRiserva },
                        set: { newValue in
                            hasRiserva = newValue
                            saveChanges()
                        }
                    ))
                    .toggleStyle(.checkbox)
                    
                    Toggle("Osservazioni", isOn: Binding(
                        get: { !hasRiserva },
                        set: { newValue in
                            hasRiserva = !newValue
                            saveChanges()
                        }
                    ))
                    .toggleStyle(.checkbox)
                    
                    Spacer()
                }
                
                Divider()
                
                if hasRiserva {
                    riservaContent
                } else {
                    osservazioniContent
                }
            }
            .padding(.vertical, 4)
        }
    }
    
    private var riservaContent: some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack {
                Text("Note Riserva")
                    .font(.subheadline)
                    .foregroundColor(.orange)
                
                Spacer()
                
                // Menu pulsanti riserve predefinite
                Menu {
                    Button("FE non sottoscritta") {
                        aggiungiRiserva(RelazionePeritaleService.fraseRiservaFENonSottoscritta)
                    }
                    Button("No FE con cause esterne") {
                        aggiungiRiserva(RelazionePeritaleService.fraseRiservaNoFEConCauseEsterne)
                    }
                    Button("No danni FE") {
                        aggiungiRiserva(RelazionePeritaleService.fraseRiservaNoFE)
                    }
                } label: {
                    Label("Aggiungi riserva", systemImage: "plus.circle")
                        .font(.caption)
                }
                .menuStyle(.borderlessButton)
            }
            
            TextEditor(text: $noteRiserva)
                .frame(minHeight: 80)
                .font(.system(size: 13))
                .padding(4)
                .background(Color.orange.opacity(0.05))
                .cornerRadius(6)
                .overlay(
                    RoundedRectangle(cornerRadius: 6)
                        .stroke(caratteriColor(noteRiserva.count, limite: limiteRiserve).opacity(0.3), lineWidth: 1)
                )
                .onChange(of: noteRiserva) { newValue in
                    salvaVersione(field: .noteRiserva, valore: newValue)
                    saveChanges()
                }
            
            HStack {
                Spacer()
                Text("\(noteRiserva.count)/\(limiteRiserve) caratteri")
                    .font(.caption)
                    .foregroundColor(caratteriColor(noteRiserva.count, limite: limiteRiserve))
            }
        }
    }
    
    private var osservazioniContent: some View {
        VStack(alignment: .leading, spacing: 4) {
            Text("Note Osservazioni")
                .font(.subheadline)
                .foregroundColor(.blue)
            
            TextEditor(text: $noteOsservazioni)
                .frame(minHeight: 80)
                .font(.system(size: 13))
                .padding(4)
                .background(Color.blue.opacity(0.05))
                .cornerRadius(6)
                .overlay(
                    RoundedRectangle(cornerRadius: 6)
                        .stroke(caratteriColor(noteOsservazioni.count, limite: limiteOsservazioni).opacity(0.3), lineWidth: 1)
                )
                .onChange(of: noteOsservazioni) { newValue in
                    salvaVersione(field: .noteOsservazioni, valore: newValue)
                    saveChanges()
                }
            
            HStack {
                Spacer()
                Text("\(noteOsservazioni.count)/\(limiteOsservazioni) caratteri")
                    .font(.caption)
                    .foregroundColor(caratteriColor(noteOsservazioni.count, limite: limiteOsservazioni))
            }
        }
    }
    
    // MARK: - Helpers UI
    
    private func caratteriColor(_ count: Int, limite: Int) -> Color {
        if count > limite {
            return .red
        } else if count > Int(Double(limite) * 0.9) {
            return .orange
        }
        return .secondary
    }
    
    // MARK: - Generazione
    
    private func generaRelazione() {
        guard let perizia = perizia else { return }
        isGeneratingRelazione = true
        
        Task { @MainActor in
            let relazione = await relazioneService.generaRelazionePeritale(sinistro: sinistro, perizia: perizia)
            self.relazionePerizia = relazione
            self.isGeneratingRelazione = false
            self.saveChanges()
        }
    }
    
    private func miglioraRelazioneConIA() {
        guard !relazionePerizia.isEmpty else { return }
        isGeneratingRelazione = true
        
        Task {
            var migliorata = ""
            
            let result = await PerxiaService.shared.miglioraRelazione(
                relazionePerizia,
                limiteCaratteri: limiteRelazione,
                streamCallback: { chunk in
                    migliorata += chunk
                }
            )
            
            await MainActor.run {
                switch result {
                case .success(let testo):
                    relazionePerizia = testo
                    saveChanges()
                case .failure(let error):
                    print("[RelazionePeritaleView] Errore IA: \(error)")
                }
                isGeneratingRelazione = false
            }
        }
    }
    
    private func generaNoteConclusive() {
        guard let perizia = perizia else { return }
        let note = relazioneService.generaNoteConclusive(sinistro: sinistro, perizia: perizia)
        noteConclusive = note
        saveChanges()
    }
    
    private func generaRiserve() {
        guard let perizia = perizia else { return }
        let riserve = relazioneService.generaRiserve(sinistro: sinistro, perizia: perizia)
        noteRiserva = riserve.joined(separator: "\n")
        saveChanges()
    }
    
    private func generaOsservazioni() {
        guard let perizia = perizia else { return }
        let osservazioni = relazioneService.generaOsservazioni(sinistro: sinistro, perizia: perizia)
        noteOsservazioni = osservazioni.joined(separator: "\n")
        saveChanges()
    }
    
    private func aggiungiRiserva(_ frase: String) {
        guard let perizia = perizia else { return }
        let importoAtto = calcolaImportoAtto()
        let fraseFormattata = relazioneService.formattaFraseRiserva(frase, importoAtto: importoAtto)
        
        if noteRiserva.isEmpty {
            noteRiserva = fraseFormattata
        } else {
            noteRiserva += "\n" + fraseFormattata
        }
        saveChanges()
    }
    
    private func calcolaImportoAtto() -> Double {
        guard let perizia = perizia else { return 0 }
        var totale: Double = 0
        
        for partita in perizia.partiteArray {
            for bene in partita.beniArray {
                if let forzato = bene.liquidazioneForzata {
                    totale += forzato.doubleValue
                } else {
                    for voce in bene.vociCostoArray where voce.indennizzabile {
                        if let vsu = voce.vsu { totale += vsu.doubleValue }
                        if let si = voce.si { totale += si.doubleValue }
                    }
                }
            }
        }
        
        return totale
    }
    
    // MARK: - Load/Save
    
    private func loadValues() {
        guard let perizia = perizia else { return }
        
        relazionePerizia = perizia.relazionePerizia ?? ""
        noteConclusive = perizia.noteConclusive ?? ""
        noteRiserva = perizia.noteRiserva ?? ""
        noteOsservazioni = perizia.noteOsservazioni ?? ""
        hasRiserva = perizia.hasRiserva
        eventoCausatoDa = perizia.eventoCausatoDa ?? ""
        determinazione = perizia.determinazione ?? ""
        
        // EVENTO CAUSATO DA: sempre precompilato se vuoto
        if eventoCausatoDa.isEmpty {
            let defaultEvento = relazioneService.generaEventoCausatoDa(sinistro: sinistro, perizia: perizia)
            if !defaultEvento.isEmpty {
                eventoCausatoDa = defaultEvento
                perizia.eventoCausatoDa = defaultEvento
                try? viewContext.save()
            }
        }
        
        // Carica versioni da Core Data
        caricaVersioniDaCoreData()
        
        // Se determinazione è vuota, prova a derivarla
        if determinazione.isEmpty {
            if let derivata = relazioneService.derivaDeterminazione(da: sinistro) {
                determinazione = derivata
                perizia.determinazione = derivata
                try? viewContext.save()
            }
        }
    }
    
    // MARK: - Generazione Automatica
    
    private func checkAutoGeneration() {
        guard let perizia = perizia else { return }
        
        // Calcola hash della perizia (basato su beni)
        let hashPerizia = calcolaHashPerizia(perizia)
        
        // Se la perizia è compilata (almeno un bene) e non abbiamo ancora generato o è cambiata
        let haBeni = !perizia.partiteArray.isEmpty || !perizia.beniBozzaArray.isEmpty
        
        if haBeni && (!hasAutoGenerated || hashPerizia != lastPeriziaHash) {
            // Genera automaticamente se relazione è vuota
            if relazionePerizia.isEmpty {
                generaRelazione()
            }
            
            hasAutoGenerated = true
            lastPeriziaHash = hashPerizia
        }
    }
    
    private func calcolaHashPerizia(_ perizia: Perizia) -> Int {
        var hash = 0
        for partita in perizia.partiteArray {
            hash ^= partita.beniArray.count.hashValue
            for bene in partita.beniArray {
                hash ^= bene.nome.hashValue
            }
        }
        hash ^= perizia.beniBozzaArray.count.hashValue
        return hash
    }
    
    // MARK: - Copia Testo
    
    private func copiaTesto(_ testo: String) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(testo, forType: .string)
    }
    
    // MARK: - Versioning
    
    enum CampoVersione {
        case relazione
        case noteConclusive
        case noteRiserva
        case noteOsservazioni
        
        var nomeCampo: String {
            switch self {
            case .relazione: return "relazionePerizia"
            case .noteConclusive: return "noteConclusive"
            case .noteRiserva: return "noteRiserva"
            case .noteOsservazioni: return "noteOsservazioni"
            }
        }
    }
    
    private func caricaVersioniDaCoreData() {
        guard let perizia = perizia else { return }
        
        // Forza refresh del context per assicurarsi di avere i dati più recenti
        viewContext.refresh(perizia, mergeChanges: true)
        
        // Carica versioni per ogni campo
        let versioniRelazioneCD = perizia.versioniPerCampo("relazionePerizia")
        versioniRelazione = versioniRelazioneCD.map { $0.contenuto }
        if !versioniRelazione.isEmpty {
            // Trova l'indice della versione corrente (ultima o quella che corrisponde al contenuto)
            if let contenutoCorrente = perizia.relazionePerizia, !contenutoCorrente.isEmpty {
                if let indice = versioniRelazione.firstIndex(of: contenutoCorrente) {
                    indiceVersioneRelazione = indice
                } else {
                    indiceVersioneRelazione = versioniRelazione.count - 1
                }
            } else {
                indiceVersioneRelazione = versioniRelazione.count - 1
            }
        } else if !relazionePerizia.isEmpty {
            // Se non ci sono versioni salvate ma c'è contenuto, crea prima versione
            versioniRelazione = [relazionePerizia]
            indiceVersioneRelazione = 0
            salvaVersioneInCoreData(field: .relazione, valore: relazionePerizia)
        }
        
        let versioniNoteConclusiveCD = perizia.versioniPerCampo("noteConclusive")
        versioniNoteConclusive = versioniNoteConclusiveCD.map { $0.contenuto }
        if !versioniNoteConclusive.isEmpty {
            if let contenutoCorrente = perizia.noteConclusive, !contenutoCorrente.isEmpty {
                if let indice = versioniNoteConclusive.firstIndex(of: contenutoCorrente) {
                    indiceVersioneNoteConclusive = indice
                } else {
                    indiceVersioneNoteConclusive = versioniNoteConclusive.count - 1
                }
            } else {
                indiceVersioneNoteConclusive = versioniNoteConclusive.count - 1
            }
        } else if !noteConclusive.isEmpty {
            versioniNoteConclusive = [noteConclusive]
            indiceVersioneNoteConclusive = 0
            salvaVersioneInCoreData(field: .noteConclusive, valore: noteConclusive)
        }
        
        let versioniNoteRiservaCD = perizia.versioniPerCampo("noteRiserva")
        versioniNoteRiserva = versioniNoteRiservaCD.map { $0.contenuto }
        if !versioniNoteRiserva.isEmpty {
            if let contenutoCorrente = perizia.noteRiserva, !contenutoCorrente.isEmpty {
                if let indice = versioniNoteRiserva.firstIndex(of: contenutoCorrente) {
                    indiceVersioneNoteRiserva = indice
                } else {
                    indiceVersioneNoteRiserva = versioniNoteRiserva.count - 1
                }
            } else {
                indiceVersioneNoteRiserva = versioniNoteRiserva.count - 1
            }
        } else if !noteRiserva.isEmpty {
            versioniNoteRiserva = [noteRiserva]
            indiceVersioneNoteRiserva = 0
            salvaVersioneInCoreData(field: .noteRiserva, valore: noteRiserva)
        }
        
        let versioniNoteOsservazioniCD = perizia.versioniPerCampo("noteOsservazioni")
        versioniNoteOsservazioni = versioniNoteOsservazioniCD.map { $0.contenuto }
        if !versioniNoteOsservazioni.isEmpty {
            if let contenutoCorrente = perizia.noteOsservazioni, !contenutoCorrente.isEmpty {
                if let indice = versioniNoteOsservazioni.firstIndex(of: contenutoCorrente) {
                    indiceVersioneNoteOsservazioni = indice
                } else {
                    indiceVersioneNoteOsservazioni = versioniNoteOsservazioni.count - 1
                }
            } else {
                indiceVersioneNoteOsservazioni = versioniNoteOsservazioni.count - 1
            }
        } else if !noteOsservazioni.isEmpty {
            versioniNoteOsservazioni = [noteOsservazioni]
            indiceVersioneNoteOsservazioni = 0
            salvaVersioneInCoreData(field: .noteOsservazioni, valore: noteOsservazioni)
        }
    }
    
    private func salvaVersione(field: CampoVersione, valore: String) {
        guard let perizia = perizia else { return }
        
        // Controlla se è diversa dall'ultima versione
        let versioniArray: [String]
        let indiceCorrente: Int
        
        switch field {
        case .relazione:
            versioniArray = versioniRelazione
            indiceCorrente = indiceVersioneRelazione
        case .noteConclusive:
            versioniArray = versioniNoteConclusive
            indiceCorrente = indiceVersioneNoteConclusive
        case .noteRiserva:
            versioniArray = versioniNoteRiserva
            indiceCorrente = indiceVersioneNoteRiserva
        case .noteOsservazioni:
            versioniArray = versioniNoteOsservazioni
            indiceCorrente = indiceVersioneNoteOsservazioni
        }
        
        // Se è uguale all'ultima versione, non salvare
        if let ultima = versioniArray.last, ultima == valore {
            return
        }
        
        // Rimuovi versioni future se siamo in mezzo alla cronologia
        let versioniCD = perizia.versioniPerCampo(field.nomeCampo)
        if indiceCorrente < versioniCD.count - 1 {
            // Elimina versioni future da Core Data
            for i in (indiceCorrente + 1)..<versioniCD.count {
                viewContext.delete(versioniCD[i])
            }
            try? viewContext.save()
        }
        
        // Rimuovi versioni future se siamo in mezzo alla cronologia
        if indiceCorrente < versioniCD.count - 1 {
            // Elimina versioni future da Core Data
            for i in (indiceCorrente + 1)..<versioniCD.count {
                viewContext.delete(versioniCD[i])
            }
            try? viewContext.save()
        }
        
        // Salva nuova versione in Core Data
        salvaVersioneInCoreData(field: field, valore: valore)
        
        // Limita a 20 versioni se necessario
        let versioniAggiornate = perizia.versioniPerCampo(field.nomeCampo)
        if versioniAggiornate.count > 20 {
            rimuoviVersioniVecchie(field: field, mantieniUltime: 20)
        }
        
        // Ricarica versioni da Core Data per sincronizzare
        ricaricaVersioniPerCampo(field: field)
    }
    
    private func ricaricaVersioniPerCampo(field: CampoVersione) {
        guard let perizia = perizia else { return }
        
        // Forza refresh
        viewContext.refresh(perizia, mergeChanges: true)
        
        let versioniCD = perizia.versioniPerCampo(field.nomeCampo)
        let contenuti = versioniCD.map { $0.contenuto }
        
        switch field {
        case .relazione:
            versioniRelazione = contenuti
            // Trova l'indice della versione corrente
            if !relazionePerizia.isEmpty {
                if let indice = contenuti.firstIndex(of: relazionePerizia) {
                    indiceVersioneRelazione = indice
                } else {
                    indiceVersioneRelazione = contenuti.count > 0 ? contenuti.count - 1 : -1
                }
            } else {
                indiceVersioneRelazione = contenuti.count > 0 ? contenuti.count - 1 : -1
            }
        case .noteConclusive:
            versioniNoteConclusive = contenuti
            if !noteConclusive.isEmpty {
                if let indice = contenuti.firstIndex(of: noteConclusive) {
                    indiceVersioneNoteConclusive = indice
                } else {
                    indiceVersioneNoteConclusive = contenuti.count > 0 ? contenuti.count - 1 : -1
                }
            } else {
                indiceVersioneNoteConclusive = contenuti.count > 0 ? contenuti.count - 1 : -1
            }
        case .noteRiserva:
            versioniNoteRiserva = contenuti
            if !noteRiserva.isEmpty {
                if let indice = contenuti.firstIndex(of: noteRiserva) {
                    indiceVersioneNoteRiserva = indice
                } else {
                    indiceVersioneNoteRiserva = contenuti.count > 0 ? contenuti.count - 1 : -1
                }
            } else {
                indiceVersioneNoteRiserva = contenuti.count > 0 ? contenuti.count - 1 : -1
            }
        case .noteOsservazioni:
            versioniNoteOsservazioni = contenuti
            if !noteOsservazioni.isEmpty {
                if let indice = contenuti.firstIndex(of: noteOsservazioni) {
                    indiceVersioneNoteOsservazioni = indice
                } else {
                    indiceVersioneNoteOsservazioni = contenuti.count > 0 ? contenuti.count - 1 : -1
                }
            } else {
                indiceVersioneNoteOsservazioni = contenuti.count > 0 ? contenuti.count - 1 : -1
            }
        }
    }
    
    private func salvaVersioneInCoreData(field: CampoVersione, valore: String) {
        guard let perizia = perizia,
              let periziaContext = perizia.managedObjectContext else { return }
        
        let versioniCD = perizia.versioniPerCampo(field.nomeCampo)
        let numeroVersione = Int16(versioniCD.count)
        
        // Usa lo stesso context della perizia per evitare errori di context diversi
        let nuovaVersione = PeriziaVersion(context: periziaContext)
        nuovaVersione.id = UUID()
        nuovaVersione.campo = field.nomeCampo
        nuovaVersione.contenuto = valore
        nuovaVersione.numeroVersione = numeroVersione
        nuovaVersione.dataCreazione = Date()
        nuovaVersione.perizia = perizia
        
        do {
            try periziaContext.save()
        } catch {
            print("[RelazionePeritaleView] Errore salvataggio versione: \(error)")
        }
    }
    
    private func rimuoviVersioniVecchie(field: CampoVersione, mantieniUltime: Int) {
        guard let perizia = perizia,
              let periziaContext = perizia.managedObjectContext else { return }
        
        let versioniCD = perizia.versioniPerCampo(field.nomeCampo)
        if versioniCD.count > mantieniUltime {
            let daEliminare = versioniCD.count - mantieniUltime
            for i in 0..<daEliminare {
                periziaContext.delete(versioniCD[i])
            }
            // Rinumera le versioni rimanenti
            for (index, versione) in versioniCD.suffix(mantieniUltime).enumerated() {
                versione.numeroVersione = Int16(index)
            }
            try? periziaContext.save()
        }
    }
    
    private func navigaVersionePrecedente(field: CampoVersione) {
        switch field {
        case .relazione:
            if indiceVersioneRelazione > 0 {
                indiceVersioneRelazione -= 1
                relazionePerizia = versioniRelazione[indiceVersioneRelazione]
                // Non salvare quando navighi, solo quando modifichi
            }
        case .noteConclusive:
            if indiceVersioneNoteConclusive > 0 {
                indiceVersioneNoteConclusive -= 1
                noteConclusive = versioniNoteConclusive[indiceVersioneNoteConclusive]
            }
        case .noteRiserva:
            if indiceVersioneNoteRiserva > 0 {
                indiceVersioneNoteRiserva -= 1
                noteRiserva = versioniNoteRiserva[indiceVersioneNoteRiserva]
            }
        case .noteOsservazioni:
            if indiceVersioneNoteOsservazioni > 0 {
                indiceVersioneNoteOsservazioni -= 1
                noteOsservazioni = versioniNoteOsservazioni[indiceVersioneNoteOsservazioni]
            }
        }
    }
    
    private func navigaVersioneSuccessiva(field: CampoVersione) {
        switch field {
        case .relazione:
            if indiceVersioneRelazione < versioniRelazione.count - 1 {
                indiceVersioneRelazione += 1
                relazionePerizia = versioniRelazione[indiceVersioneRelazione]
            }
        case .noteConclusive:
            if indiceVersioneNoteConclusive < versioniNoteConclusive.count - 1 {
                indiceVersioneNoteConclusive += 1
                noteConclusive = versioniNoteConclusive[indiceVersioneNoteConclusive]
            }
        case .noteRiserva:
            if indiceVersioneNoteRiserva < versioniNoteRiserva.count - 1 {
                indiceVersioneNoteRiserva += 1
                noteRiserva = versioniNoteRiserva[indiceVersioneNoteRiserva]
            }
        case .noteOsservazioni:
            if indiceVersioneNoteOsservazioni < versioniNoteOsservazioni.count - 1 {
                indiceVersioneNoteOsservazioni += 1
                noteOsservazioni = versioniNoteOsservazioni[indiceVersioneNoteOsservazioni]
            }
        }
    }
    
    private func saveChanges() {
        guard let perizia = perizia else { return }
        
        perizia.relazionePerizia = relazionePerizia.isEmpty ? nil : relazionePerizia
        perizia.noteConclusive = noteConclusive.isEmpty ? nil : noteConclusive
        perizia.noteRiserva = noteRiserva.isEmpty ? nil : noteRiserva
        perizia.noteOsservazioni = noteOsservazioni.isEmpty ? nil : noteOsservazioni
        perizia.hasRiserva = hasRiserva
        perizia.eventoCausatoDa = eventoCausatoDa.isEmpty ? nil : eventoCausatoDa
        perizia.determinazione = determinazione.isEmpty ? nil : determinazione
        
        do {
            try viewContext.save()
        } catch {
            print("[RelazionePeritaleView] Errore salvataggio: \(error)")
        }
    }
}
